app = "meeting-minutes-app"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[deploy]
  release_command = "python backend/db_migrate.py"

[env]
  PORT = "5000"
  HF_TOKEN = ""
  OPENAI_API_KEY = ""
  FLASK_ENV = "production"
  FLASK_DEBUG = "0"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[vm]
  memory = "1024" # Increase memory to 1GB
