[phases.setup]
nixPkgs = ["python38", "ffmpeg"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements-railway.txt"]

[phases.build]
cmds = ["cd UI && npm install && npm run build && cd .."]

[start]
cmd = "cd backend && gunicorn --worker-tmp-dir /tmp --bind 0.0.0.0:$PORT app:app"
