name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Display environment variables
      run: |
        echo "HF_TOKEN: $HF_TOKEN"
        echo "OPENAI_API_KEY: $OPENAI_API_KEY"
        
    - name: Run tests
      run: |
        pytest tests/ --cov=backend --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml